config/routes.rb
Rails.application.routes.draw do
  get 'memes/index'
  	devise_for :users
  # devise_for :users, controllers: {
  #       sessions: 'users/sessions'
  #     }
  #   end

  resources :friends
  # get 'home/index'
  root 'home#index'
  # get 'friends#index'

  resources :memes, only: [:index]
  get 'memes/new_meme', to: 'memes#new_meme', as: :new_meme
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
	validates :first_name, :last_name, :email, :phone, :instagram, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends

	validates :password, length: { minimum: 8 }, if: -> { new_record? || !password.nil? }
  	validates :password, format: { with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&#])[A-Za-z\d@$!%*?&#]{8,}\z/, message: "must include at least one uppercase letter, one lowercase letter, one digit, and one special character" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def index
    
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	require 'net/http'
	require 'json'
	def index

		url = URI("https://meme-api.com/gimme")
		response = Net::HTTP.get(url)
		meme_data = JSON.parse(response)

		if response_successful?(meme_data)
			@home_meme = {
				'url' => meme_data['url'],
				'title' => meme_data['title'],
				'author' => meme_data['author']
			}
		else
			@home_meme = nil
			flash[:alert] = "No meme available at the moment."
		end

		render :index
	end

	private

	def response_successful?(meme_data)
		meme_data['url'].present? && meme_data['title'].present? && meme_data['author'].present?
	end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  def index
    @meme = fetch_memes
  end

  # def new_meme
  #   @meme = fetch_memes
  #   respond_to do |format|
  #     format.js # This will look for a file named `new_meme.js.erb`
  #   end
  # end

  private

  def fetch_memes
    require 'uri'
    require 'net/http'

    url = URI("https://humor-jokes-and-memes.p.rapidapi.com/memes/random?keywords=rocket&number=3&media-type=image&keywords-in-image=false&min-rating=4")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["x-rapidapi-key"] = '9eeabd3ebdmsh2d8d9a8730f6ceep123088jsnb48c14de2a8a'
    request["x-rapidapi-host"] = 'humor-jokes-and-memes.p.rapidapi.com'

    response = http.request(request)
  #   memes = JSON.parse(response.body)
 	# @meme = memes.is_a?(Array) ? memes.first : memes # Ensure `@meme` is a single item
    
 	if response.is_a?(Net::HTTPSuccess)
 		memes = JSON.parse(response.body)
 		@meme = memes.is_a?(Array) ? memes.first : memes # Ensure `@meme` is a single item
    else
      	@meme = nil
    end
    
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # Skip other Devise actions if needed
  skip_before_action :verify_authenticity_token, only: [:create]

  # Override the create method to handle login-specific errors
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    respond_with resource, location: after_sign_in_path_for(resource)
  rescue StandardError => e
    flash[:alert] = "Invalid email or password"
    render :new
  end

  # Ensure proper redirection after successful sign in
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end

  # Ensure the correct parameters are permitted
  protected

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/friends/_form.html.erb
<div class="container mt-2">
  <div class="card mx-auto" style="max-width: 500px">
    <div class="card-body">
     
      <%= form_with(model: friend, local: true) do |form| %>
        <% if friend.errors.any? %>
          <div class="alert alert-danger">
            <h4 class="alert-heading"><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h4>
            <ul>
              <% friend.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-3">
          <%= form.label :first_name, class: "form-label" %>
          <%= form.text_field :first_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :last_name, class: "form-label" %>
          <%= form.text_field :last_name, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :phone, class: "form-label" %>
          <%= form.text_field :phone, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.label :instagram, class: "form-label" %>
          <%= form.text_field :instagram, class: "form-control" %>
        </div>

        <div class="mb-3">
          <%= form.hidden_field :user_id, value: current_user.id %>
        </div>
        

        <div class="d-grid">
          <%= form.submit "Save", class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/friends/_friend.html.erb
<tr id="<%= dom_id(friend) %>">
  <td><%= link_to friend.first_name + " " + friend.last_name, friend %> </td>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.instagram %></td>
 
  <td><%= link_to "Unfriend", friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
</tr>

app/views/friends/edit.html.erb
<h3 class="text-center">Editing friend</h3>

<%= render "form", friend: @friend %>

<br>

<div class="text-center" style="max-width: 500px; margin: auto; margin-bottom: 20px;">
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %> |
  <%= link_to "Unfriend", @friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
</div>

app/views/friends/index.html.erb
	 <table class="table table-hover ">
	 	<thead class="table-dark">
	 		<tr>
	 			<th>Name</th>
	 			<th>Email</th>
	 			<th>Phone</th>
	 			<th>Instagram</th>
	 			<th>Unfriend</th>
	 		</tr>
	 	</thead>
	 	<tbody id="friends">
	 		<% @friends.each do |friend| %>
	 		<% if friend.user == current_user %>
	 		<%= render partial: "friend", locals: { friend: friend } %>
	 		<% end %>
	 		<%end%>
	 	</tbody>
	 </table>

	 <%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>

app/views/friends/new.html.erb
<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

<h3 class="text-center">Add New Friend</h3>

<%= render "form", friend: @friend %>

<br>

app/views/friends/show.html.erb
<div class="card mb-3" style="max-width: 600px; margin: auto;">
  <div class="card-body">
    <h3 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h3>
    <p class="card-text">
      <strong>Email:</strong> <%= @friend.email %><br>
      <strong>Phone:</strong> <%= @friend.phone %><br>
      <strong>Instagram:</strong> <%= @friend.instagram %>
    </p>
  </div>
  <div class="card-footer text-center">
    <div class="d-flex justify-content-center gap-2">
      <%= link_to "Modify", edit_friend_path(@friend), class: "btn btn-secondary" %>
      <%= link_to "All Friends", friends_path, class: "btn btn-success" %>
      <%= button_to "Unfriend", @friend, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class:"nav-link" %>
          </li>    

         <!--  <li class="nav-item">
            <%= link_to 'Memes', memes_index_path, class:"nav-link" %>
          </li>   -->
	        
          <li class="nav-item">
            <%= link_to 'Add friend', new_friend_path, class:"nav-link" %>
          </li> 
	        <li class="nav-item">
	        	<%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
	        </li> 
	        <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li> 
	    <% else %>
	        <li class="nav-item">
	        	<%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
	        </li> 
	        <li class="nav-item">
	        	<%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
	        </li> 
	     <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
<h1>Random Memes</h1>

app/views/home/index.html.erb
<div class="container" style="height: 95vh;">
  <div class="card mx-auto d-flex align-items-center justify-content-center" style="max-width: 500px; height: 80%;">
    <div class="card-body text-center">
      <% if @home_meme %>
        <div class="mb-3">
          <img src="<%= @home_meme['url'] %>" class="card-img-top" alt="Meme image" style="max-height: 50vh; object-fit: contain;">
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= @home_meme['title'] %></h5>
          <p class="card-text">By: <%= @home_meme['author'] %></p>
        </div>
      <% else %>
        <p>No meme available at the moment.</p>
      <% end %>
    </div>
  </div>

  <div class="text-center mt-3">
    <%= button_to 'Next Meme', root_path, method: :get, class: 'btn btn-primary' %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends app</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
  	<%= render 'home/header'%>
  	<div class="container"><br/>
      <% if notice %>
        <%= render 'layouts/alerts'%>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/memes/_meme.html.erb
<div class="mb-3">
  <img src="<%= meme['url'] %>" class="card-img-top" alt="Meme image">
</div>
<div class="card-body">
  <p class="card-text"><%= meme['description'] %></p>
</div>

app/views/memes/index.html.erb
<div class="container">
  <div class="card mx-auto" style="max-width: 500px;">
    <div class="card-body">
      <% if @meme %>
        <div class="mb-3 text-center">
          <img src="<%= @meme['url'] %>" class="card-img-top" alt="Meme image">
        </div>
        <div class="card-body">
          <p class="card-text"><%= @meme['description'] %></p>
        </div>
        <div class="text-center mt-3">
          <%= button_to 'Next Meme', new_meme_path, method: :get, remote: true, class: 'btn btn-primary' %>
        </div>
      <% else %>
        <div class="alert alert-warning text-center" role="alert">
          No meme available at the moment.
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/memes/new_meme.js.erb
$("#meme-container").html("<%= j(render partial: 'meme', locals: { meme: @meme }) %>");